---
foreman:
  # Based on grep 'foreman::plugin ' puppet-foreman/manifests/plugin/*.pp | cut -d\' -f2
  plugins:
    acd:
      github_org: 'ATIX-AG'
      rpm: true
    ansible:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/ansible'
    azure_rm:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/azure'
    bootdisk:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/bootdisk'
    column_view:
      # TODO: drop?
      deb: true
      rpm: true
    concrete:
      github_org: 'timogoebel'
      installer: false
      rpm: true
    datacenter:
      installer: false
      deb: true
      rpm: true
      github_team: 'theforeman/foreman-datacenter'
    default_hostgroup:
      deb: true
      rpm: true
      github_team: 'theforeman/foreman_default_hostgroup'
    dhcp_browser:
      deb: true
      rpm: true
      github_team: 'theforeman/dhcp-browser'
    discovery:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/discovery'
    dlm:
      github_org: 'dm-drogeriemarkt'
      rpm: true
    expire_hosts:
      deb: true
      rpm: true
      github_team: 'theforeman/expire-hosts'
    fog_proxmox:
      installer: false
      deb: true
      rpm: true
      github_team: 'theforeman/proxmox'
    git_templates:
      github_org: 'dm-drogeriemarkt'
      rpm: true
    google:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/google'
    graphite:
      installer: false
      deb: true
      rpm: true
    hooks:
      deb: true
      rpm: true
      github_team: 'theforeman/foreman-hooks'
    host_extra_validator:
      rpm: true
      github_team: 'theforeman/host-extra-validator'
    katello:
      name: 'katello'
      rpm: true
      translations: true
      github_org: 'Katello'
      rpm_directory: 'katello'
    kubevirt:
      rpm: true
      translations: true
      github_team: 'theforeman/kubevirt'
    leapp:
      rpm: true
      translations: true
      github_team: 'theforeman/foreman_leapp'
    monitoring:
      deb: true
      rpm: true
      github_team: 'theforeman/monitoring'
    netbox:
      github_org: 'dm-drogeriemarkt'
      rpm: true
    omaha:
      deb: true
      rpm: true
      github_team: 'theforeman/omaha'
    openscap:
      rpm: true
      translations: true
      github_team: 'theforeman/openscap'
    probing:
      github_org: 'adamruzicka'
      installer: false
      rpm: true
    puppet:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/puppet'
    puppetdb:
      name: 'puppetdb_foreman'
      deb: true
      rpm: true
      github_team: 'theforeman/puppetdb'
    remote_execution:
      deb: true
      rpm: true
      puppet_acceptance_tests: 'foreman_rex_cockpit'
      translations: true
      github_team: 'theforeman/remote-execution'
    rescue:
      github_org: 'dm-drogeriemarkt'
      deb: true
      rpm: true
    rh_cloud:
      rpm: true
      rpm_directory: 'katello'
      translations: true
      github_team: 'theforeman/rh-cloud'
    salt:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/salt'
    scc_manager:
      github_org: 'ATIX-AG'
      rpm: true
      rpm_directory: 'katello'
      translations: true
    setup:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/foreman-setup'
    snapshot_management:
      github_org: 'ATIX-AG'
      rpm: true
      translations: true
    statistics:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/statistics'
    supervisory_authority:
      installer: false
      rpm: true
      github_team: 'theforeman/supervisory_authority'
    tasks:
      name: foreman-tasks
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/foreman-tasks'
    templates:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/foreman_templates'
    vault:
      github_org: 'dm-drogeriemarkt'
      rpm: true
    virt_who_configure:
      rpm: true
      rpm_directory: 'katello'
      translations: true
      github_team: 'theforeman/virt-who-configure'
    vmwareannotations:
      installer: false
      rpm: true
      github_team: 'theforeman/vmware-annotations'
    webhooks:
      deb: true
      rpm: true
      github_team: 'theforeman/webhooks'
    wreckingball:
      github_org: 'dm-drogeriemarkt'
      rpm: true

smart_proxy:
  # grep -R 'foreman_proxy::plugin::provider ' puppet-foreman_proxy/manifests/plugin | cut -d\' -f2
  providers:
    dhcp_bluecat:
      installer: false
      rpm: true
    dhcp_device42:
      installer: false
      rpm: true
    dhcp_dnsmasq:
      installer: false
      deb: true
      rpm: true
    dhcp_infoblox:
      deb: true
      rpm: true
    dhcp_remote_isc:
      deb: true
      rpm: true
    dns_dnsmasq:
      installer: false
      deb: true
      rpm: true
    dns_infoblox:
      deb: true
      rpm: true
    dns_powerdns:
      deb: true
      rpm: true
    dns_route53:
      installer: false
      deb: true
      rpm: true
    realm_ad:
      name: smart_proxy_realm_ad_plugin
      installer: false
      rpm: true
  modules:
    acd:
      github_org: 'ATIX-AG'
      rpm: true
    ansible:
      deb: true
      rpm: true
      puppet_acceptance_tests: true
      github_team: 'theforeman/ansible'
    container_gateway:
      # Note: not exposed directly in the installer
      github_org: 'Katello'
      rpm: true
    discovery:
      deb: true
      rpm: true
      puppet_acceptance_tests: true
      github_team: 'theforeman/discovery'
    dynflow:
      deb: true
      rpm: true
      puppet_acceptance_tests: true
      github_team: 'theforeman/remote-execution'
    monitoring:
      deb: true
      rpm: true
      github_team: 'theforeman/monitoring'
    omaha:
      deb: true
      rpm: true
      github_team: 'theforeman/omaha'
    openscap:
      rpm: true
      puppet_acceptance_tests: true
      github_team: 'theforeman/openscap'
    probing:
      url: 'https://github.com/adamruzicka/smart-proxy-probing'
      installer: false
      rpm: 'rubygem-smart-proxy-probing'
    pulp:
      # Note: not exposed directly in the installer
      rpm: true
      github_team: 'theforeman/pulp'
    remote_execution_ssh:
      deb: true
      rpm: true
      # TODO: also remote_execution_script_pull_mqtt
      puppet_acceptance_tests: 'remote_execution_script'
      github_team: 'theforeman/remote-execution'
    salt:
      deb: true
      rpm: true
      github_team: 'theforeman/salt'
    shellhooks:
      deb: true
      rpm: true
      github_team: 'theforeman/webhooks'

cli:
  # grep '  foreman::cli::plugin' puppet-foreman/manifests/cli/*.pp | cut -d\' -f2
  plugins:
    foreman_ansible:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/ansible'
    foreman_azure_rm:
      rpm: true
      url: 'https://github.com/theforeman/hammer_cli_foreman_azure_rm'
      translations: true
      github_team: 'theforeman/azure'
    # TODO: foreman_bootdisk?
    foreman_discovery:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/discovery'
    foreman_google:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/google'
    foreman_kubevirt:
      rpm: true
      puppet_acceptance_tests: false
      translations: true
      github_team: 'theforeman/kubevirt'
    foreman_openscap:
      rpm: true
      url: 'https://github.com/theforeman/hammer_cli_foreman_openscap'
      puppet_acceptance_tests: false
      translations: true
      github_team: 'theforeman/openscap'
    foreman_puppet:
      deb: true
      rpm: true
      translations: https://www.transifex.com/foreman/foreman/hammer-cli-foreman-puppet/
      github_team: 'theforeman/puppet'
    foreman_remote_execution:
      deb: true
      rpm: true
      url: 'https://github.com/theforeman/hammer_cli_foreman_remote_execution'
      translations: https://www.transifex.com/foreman/foreman/hammer-cli-foreman-remote-execution/
      github_team: 'theforeman/remote-execution'
    foreman_ssh:
      deb: true
      rpm: true
      # No translations
    foreman_tasks:
      deb: true
      rpm: true
      translations: true
      github_team: 'theforeman/foreman-tasks'
    foreman_templates:
      deb: true
      rpm: true
      translations: https://www.transifex.com/foreman/foreman/hammer-cli-foreman-templates/
      github_team: 'theforeman/foreman_templates'
    foreman_virt_who_configure:
      rpm: true
      rpm_directory: 'katello'
      puppet_acceptance_tests: false
      translations: https://www.transifex.com/foreman/foreman/hammer-cli-foreman-virt-who-configure/
      github_team: 'theforeman/virt-who-configure'
    foreman_webhooks:
      deb: true
      rpm: true
      # No translations: https://github.com/theforeman/hammer-cli-foreman-webhooks/issues/5
      github_team: 'theforeman/webhooks'
    katello:
      rpm: true
      rpm_directory: 'katello'
      github_org: 'Katello'
      translations: https://www.transifex.com/foreman/foreman/hammer-cli-katello/

installer:
  modules:
    candlepin:
    certs:
    dhcp:
    dns:
    foreman:
    foreman_proxy:
    foreman_proxy_content:
    git:
    katello:
    pulpcore:
    puppet:
    puppetserver_foreman:
    qpid:
    tftp:

auxiliary:
  foreman-documentation:
    description: "Official Katello documentation"
  forklift:
    description: "Tooling to deploy Foreman, primarily in test and development environments"
  theforeman.org:
    description: "Official website, including the official manual"
